# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('short_description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('thumbnail_image', models.CharField(max_length=200)),
                ('hero_image', models.CharField(max_length=200)),
                ('aplly_form', models.CharField(max_length=200)),
                ('long_description', markdownx.models.MarkdownxField()),
                ('application_start_date', models.DateTimeField(blank=True, null=True)),
                ('application_end_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('photo', models.CharField(max_length=200)),
                ('personal_page', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('thumbnail_image', models.CharField(max_length=200)),
                ('hero_image', models.CharField(max_length=200)),
                ('motto', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('short_description', models.TextField()),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('thumbnail_image', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=200)),
                ('long_description', markdownx.models.MarkdownxField()),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ggit_platform.Region')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=100)),
                ('short_description', models.TextField()),
                ('subtitle', models.TextField()),
                ('hero_image', models.CharField(max_length=200)),
                ('long_description', markdownx.models.MarkdownxField()),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ggit_platform.Region'),
        ),
        migrations.AddField(
            model_name='event',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ggit_platform.Region'),
        ),
    ]
