# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ggit_platform', '0002_auto_20170727_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='hero_image',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
