# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 10:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ggit_platform', '0003_story_hero_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='aplly_form',
            new_name='apply_form',
        ),
    ]
